// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: msgData.proto

package msgData

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgC2S_MsgType int32

const (
	MsgC2S_join MsgC2S_MsgType = 0
	MsgC2S_send MsgC2S_MsgType = 1
	MsgC2S_quit MsgC2S_MsgType = 2
)

// Enum value maps for MsgC2S_MsgType.
var (
	MsgC2S_MsgType_name = map[int32]string{
		0: "join",
		1: "send",
		2: "quit",
	}
	MsgC2S_MsgType_value = map[string]int32{
		"join": 0,
		"send": 1,
		"quit": 2,
	}
)

func (x MsgC2S_MsgType) Enum() *MsgC2S_MsgType {
	p := new(MsgC2S_MsgType)
	*p = x
	return p
}

func (x MsgC2S_MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgC2S_MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgData_proto_enumTypes[0].Descriptor()
}

func (MsgC2S_MsgType) Type() protoreflect.EnumType {
	return &file_msgData_proto_enumTypes[0]
}

func (x MsgC2S_MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgC2S_MsgType.Descriptor instead.
func (MsgC2S_MsgType) EnumDescriptor() ([]byte, []int) {
	return file_msgData_proto_rawDescGZIP(), []int{1, 0}
}

type MsgData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []byte `protobuf:"bytes,1,opt,name=datas,proto3" json:"datas,omitempty"`
}

func (x *MsgData) Reset() {
	*x = MsgData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgData) ProtoMessage() {}

func (x *MsgData) ProtoReflect() protoreflect.Message {
	mi := &file_msgData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgData.ProtoReflect.Descriptor instead.
func (*MsgData) Descriptor() ([]byte, []int) {
	return file_msgData_proto_rawDescGZIP(), []int{0}
}

func (x *MsgData) GetDatas() []byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

// types : 1
type MsgC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nick    string         `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Msg     string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time    int64          `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`
	MsgType MsgC2S_MsgType `protobuf:"varint,4,opt,name=msgType,proto3,enum=msgData.MsgC2S_MsgType" json:"msgType,omitempty"`
}

func (x *MsgC2S) Reset() {
	*x = MsgC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgC2S) ProtoMessage() {}

func (x *MsgC2S) ProtoReflect() protoreflect.Message {
	mi := &file_msgData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgC2S.ProtoReflect.Descriptor instead.
func (*MsgC2S) Descriptor() ([]byte, []int) {
	return file_msgData_proto_rawDescGZIP(), []int{1}
}

func (x *MsgC2S) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *MsgC2S) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgC2S) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *MsgC2S) GetMsgType() MsgC2S_MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgC2S_join
}

// types : 2
type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass  string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	State int32  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_msgData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_msgData_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Account) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *Account) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// types : 3
type AccountAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int32 `protobuf:"varint,1,opt,name=Ack,proto3" json:"Ack,omitempty"`
}

func (x *AccountAck) Reset() {
	*x = AccountAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAck) ProtoMessage() {}

func (x *AccountAck) ProtoReflect() protoreflect.Message {
	mi := &file_msgData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAck.ProtoReflect.Descriptor instead.
func (*AccountAck) Descriptor() ([]byte, []int) {
	return file_msgData_proto_rawDescGZIP(), []int{3}
}

func (x *AccountAck) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_msgData_proto protoreflect.FileDescriptor

var file_msgData_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x43, 0x32, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x10, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x31,
	0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x6d, 0x73, 0x67, 0x43, 0x32, 0x53,
	0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x27, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x6a, 0x6f, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x74, 0x10, 0x02, 0x22, 0x47, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x63,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x41, 0x63, 0x6b, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgData_proto_rawDescOnce sync.Once
	file_msgData_proto_rawDescData = file_msgData_proto_rawDesc
)

func file_msgData_proto_rawDescGZIP() []byte {
	file_msgData_proto_rawDescOnce.Do(func() {
		file_msgData_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgData_proto_rawDescData)
	})
	return file_msgData_proto_rawDescData
}

var file_msgData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msgData_proto_goTypes = []interface{}{
	(MsgC2S_MsgType)(0), // 0: msgData.msgC2S.MsgType
	(*MsgData)(nil),     // 1: msgData.msgData
	(*MsgC2S)(nil),      // 2: msgData.msgC2S
	(*Account)(nil),     // 3: msgData.account
	(*AccountAck)(nil),  // 4: msgData.accountAck
}
var file_msgData_proto_depIdxs = []int32{
	0, // 0: msgData.msgC2S.msgType:type_name -> msgData.msgC2S.MsgType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msgData_proto_init() }
func file_msgData_proto_init() {
	if File_msgData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgData_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgData_proto_goTypes,
		DependencyIndexes: file_msgData_proto_depIdxs,
		EnumInfos:         file_msgData_proto_enumTypes,
		MessageInfos:      file_msgData_proto_msgTypes,
	}.Build()
	File_msgData_proto = out.File
	file_msgData_proto_rawDesc = nil
	file_msgData_proto_goTypes = nil
	file_msgData_proto_depIdxs = nil
}
